services:
  mcp-evolution:
    container_name: mcp_evolution_api
    image: ghcr.io/intuitivephella/mcp-evolution-api:latest
    restart: unless-stopped
    ports:
      - "3001:3001" # Porta local para testes (opcional, já que usará Traefik)
    environment:
      - NODE_ENV=production
      - PORT=3001
      - TZ=America/Sao_Paulo

      # Configuração de conexão com Evolution API
      - EVOLUTION_API_URL=https://evolution.gwan.com.br
      - EVOLUTION_API_KEY=pazdeDeus@2025
      - EVOLUTION_API_INSTANCE=Agente
      - ENABLE_WEBSOCKET=true

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/status"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 30s

    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 512M

    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=gwan"
      - "traefik.http.routers.mcp-evolution.rule=Host(`mcp-evolution.gwan.com.br`)"
      - "traefik.http.routers.mcp-evolution.entrypoints=websecure"
      - "traefik.http.routers.mcp-evolution.tls=true"
      - "traefik.http.routers.mcp-evolution.tls.certresolver=letsencrypt"
      - "traefik.http.services.mcp-evolution.loadbalancer.server.port=3001"

      # Middlewares opcionais para segurança (como no bff)
      - "traefik.http.middlewares.mcp-evolution-headers.headers.sslRedirect=true"
      - "traefik.http.middlewares.mcp-evolution-headers.headers.stsSeconds=31536000"
      - "traefik.http.middlewares.mcp-evolution-headers.headers.browserXssFilter=true"
      - "traefik.http.middlewares.mcp-evolution-headers.headers.contentTypeNosniff=true"
      - "traefik.http.middlewares.mcp-evolution-headers.headers.forceSTSHeader=true"
      - "traefik.http.middlewares.mcp-evolution-headers.headers.stsIncludeSubdomains=true"
      - "traefik.http.middlewares.mcp-evolution-headers.headers.stsPreload=true"

      - "traefik.http.routers.mcp-evolution.middlewares=mcp-evolution-headers"

    networks:
      - gwan

networks:
  gwan:
    external: true
